import IrrationalityAr.CriteriaLattice


open scoped BigOperators

/-!
# Equivalence class problem

This file contains the project statement for the inverse-symmetry theorem,
which we now call the **equivalence class problem**.

Mathematically, for irrational `α`, the target theorem is

`A β = A α ↔ ∃ m : ℤ, β = α + 2m ∨ β = -α + 2m`.

The file is organized so that the already-formalized continued-fraction bridge
is used through `A_eq_odd_convergent_or_semiconvergent`, and the new work is
isolated in one lemma:

`oddCFDenoms_rigid_on_Icc`.

That lemma is the general first-deviation lemma for parity-filtered principal
and intermediate convergent denominators.
-/

namespace IrrationalityAr

/-- The equivalence class of `α` under the invariant `A`. -/
def AEquivClass (α : ℝ) : Set ℝ :=
  {β : ℝ | A β = A α}

/-- The obvious symmetry orbit generated by period `2` and reflection. -/
def twoShift (m : ℤ) : ℝ :=
  (2 : ℝ) * (m : ℝ)

/-- The expected equivalence class of an irrational number. -/
def symmetryClass (α : ℝ) : Set ℝ :=
  {β : ℝ | ∃ m : ℤ, β = α + twoShift m ∨ β = -α + twoShift m}

/-- Shifted denominator set attached to `A_α`.

The shift by one is chosen so that the continued-fraction theorem says that
`q ∈ hitDenoms α` exactly when `q` is the denominator of a parity-selected
principal or intermediate convergent. -/
def hitDenoms (α : ℝ) : Set ℕ :=
  {q : ℕ | 2 ≤ q ∧ q - 1 ∈ A α}

/-- Equality of `A`-sets gives equality of hit-denominator sets. -/
theorem hitDenoms_eq_of_A_eq {α β : ℝ} (hA : A β = A α) :
    hitDenoms β = hitDenoms α := by
  ext q
  simp [hitDenoms, hA]

/-- If `A_β = A_α` and `α` is irrational, then `β` is irrational. -/
theorem irrational_of_A_eq_irrational {α β : ℝ}
    (hαirr : IsIrrational α) (hA : A β = A α) :
    IsIrrational β := by
  intro hβrat
  have hβAP : IsEventuallyAP (A β) :=
    (rational_iff_eventuallyAP β).mp hβrat
  have hβInf : ContainsInfiniteAP (A β) :=
    eventuallyAP_containsInfiniteAP hβAP
  have hαInf : ContainsInfiniteAP (A α) := by
    rwa [← hA]
  exact irrational_no_infiniteAP hαirr hαInf

/-- The already-formalized continued-fraction bridge, repackaged as equality of
hit-denominators and parity-filtered CF denominators. -/
theorem hitDenoms_eq_oddCFDenoms {α : ℝ}
    (hαpos : 0 < α) (hαirr : IsIrrational α) :
    hitDenoms α = oddCFDenoms α := by
  ext q
  constructor
  · intro hqmem
    rcases hqmem with ⟨hq2, hAq⟩
    have hclass :
        q - 1 ∈
          {n : ℕ | ∃ p q' : ℕ,
            n = q' - 1 ∧ 2 ≤ q' ∧ ReducedFraction p q' ∧
              IsConvergentOrSemiconvergent α p q' ∧ Odd p} := by
      rw [← A_eq_odd_convergent_or_semiconvergent hαpos hαirr]
      exact hAq
    rcases hclass with ⟨p, q', hn, hq', hred, hcf, hpodd⟩
    have hqq' : q' = q := by
      omega
    subst q'
    exact ⟨p, hq2, hred, hcf, hpodd⟩
  · rintro ⟨p, hq2, hred, hcf, hpodd⟩
    refine ⟨hq2, ?_⟩
    have hclass :
        q - 1 ∈
          {n : ℕ | ∃ p q' : ℕ,
            n = q' - 1 ∧ 2 ≤ q' ∧ ReducedFraction p q' ∧
              IsConvergentOrSemiconvergent α p q' ∧ Odd p} := by
      exact ⟨p, q, rfl, hq2, hred, hcf, hpodd⟩
    rw [A_eq_odd_convergent_or_semiconvergent hαpos hαirr]
    exact hclass

/-- Rigidity of the parity-filtered principal/intermediate denominator set
on the normalized interval `[1,2]`.

This is now only a wrapper around:
1. existence of a first differing canonical partial quotient;
2. the hard first-deviation denominator lemma above. -/
theorem oddCFDenoms_rigid_on_Icc {x y : ℝ}
    (hxirr : IsIrrational x) (hyirr : IsIrrational y)
    (hxI : x ∈ Set.Icc (1 : ℝ) 2)
    (hyI : y ∈ Set.Icc (1 : ℝ) 2)
    (hden : oddCFDenoms x = oddCFDenoms y) :
    x = y := by
  by_contra hxy

  have hxpos : 0 < x := by
    exact lt_of_lt_of_le (by norm_num) hxI.1

  have hypos : 0 < y := by
    exact lt_of_lt_of_le (by norm_num) hyI.1

  rcases exists_firstDiff_simplePartialQuotient_of_ne
      hxpos hypos hxirr hyirr hxy with
    ⟨j, hprefix, hdiff⟩

  have hne : oddCFDenoms x ≠ oddCFDenoms y :=
    oddCFDenoms_ne_of_firstDiff_simplePartialQuotient
      hxirr hyirr hxI hyI hprefix hdiff

  exact hne hden

/-- Normalized equivalence-class theorem.

Inside `[1,2]`, equality of `A`-sets forces equality of the real numbers. -/
theorem equivalence_class_problem_normalized {α β : ℝ}
    (hαirr : IsIrrational α)
    (hαI : α ∈ Set.Icc (1 : ℝ) 2)
    (hβI : β ∈ Set.Icc (1 : ℝ) 2)
    (hA : A β = A α) :
    β = α := by
  have hβirr : IsIrrational β :=
    irrational_of_A_eq_irrational hαirr hA
  have hαpos : 0 < α := lt_of_lt_of_le (by norm_num) hαI.1
  have hβpos : 0 < β := lt_of_lt_of_le (by norm_num) hβI.1
  have hHit : hitDenoms β = hitDenoms α :=
    hitDenoms_eq_of_A_eq hA
  have hOdd : oddCFDenoms β = oddCFDenoms α := by
    calc
      oddCFDenoms β = hitDenoms β :=
        (hitDenoms_eq_oddCFDenoms hβpos hβirr).symm
      _ = hitDenoms α := hHit
      _ = oddCFDenoms α :=
        hitDenoms_eq_oddCFDenoms hαpos hαirr
  exact oddCFDenoms_rigid_on_Icc hβirr hαirr hβI hαI hOdd

/-- Iff form of the normalized equivalence-class theorem.  On the normalized
interval `[1,2]`, equality of floor-sum divisibility sets is exactly equality
of parameters. -/
theorem equivalence_class_problem_normalized_iff {α β : ℝ}
    (hαirr : IsIrrational α)
    (hαI : α ∈ Set.Icc (1 : ℝ) 2)
    (hβI : β ∈ Set.Icc (1 : ℝ) 2) :
    A β = A α ↔ β = α := by
  constructor
  · exact equivalence_class_problem_normalized hαirr hαI hβI
  · intro h
    simp [h]

/-! ## Symmetry and normalization interface

The next lemmas are the elementary period/reflection layer and the real-line
normalization layer. They are placed here as theorem stubs so that the final
statement has the intended project shape. If these already exist in another
module later, replace these proofs by imports and exact references.
-/

/-- Periodicity modulo `2`. -/
private theorem floorMul_add_twoShift (r : ℝ) (m : ℤ) (k : ℕ) :
    floorMul (r + twoShift m) k =
      floorMul r k + (k : ℤ) * (2 * m) := by
  unfold floorMul twoShift
  have harg :
      (k : ℝ) * (r + (2 : ℝ) * (m : ℝ)) =
        (k : ℝ) * r + (((k : ℤ) * (2 * m) : ℤ) : ℝ) := by
    norm_num
    ring
  rw [harg]
  rw [add_comm, Int.floor_intCast_add]
  ring

private theorem floorSum_add_twoShift (r : ℝ) (m : ℤ) (n : ℕ) :
    floorSum (r + twoShift m) n =
      floorSum r n +
        (2 * m) * ∑ k ∈ Finset.Icc 1 n, (k : ℤ) := by
  unfold floorSum
  rw [Finset.sum_congr rfl (fun k _ => floorMul_add_twoShift r m k)]
  rw [Finset.sum_add_distrib]
  congr 1
  rw [Finset.mul_sum]
  congr 1
  ext k
  ring

private theorem two_mul_sum_Icc_one_id (n : ℕ) :
    2 * (∑ k ∈ Finset.Icc 1 n, (k : ℤ)) =
      (n : ℤ) * ((n : ℤ) + 1) := by
  induction n with
  | zero =>
      simp
  | succ n ih =>
      rw [Finset.sum_Icc_succ_top (by omega : 1 ≤ n + 1)
        (fun k : ℕ => (k : ℤ))]
      rw [mul_add, ih]
      norm_num
      ring

private theorem dvd_shift_floorSum_addend (m : ℤ) (n : ℕ) :
    (n : ℤ) ∣
      (2 * m) * ∑ k ∈ Finset.Icc 1 n, (k : ℤ) := by
  let s : ℤ := ∑ k ∈ Finset.Icc 1 n, (k : ℤ)
  have hs : 2 * s = (n : ℤ) * ((n : ℤ) + 1) := by
    simpa [s] using two_mul_sum_Icc_one_id n
  have hadd :
      (2 * m) * s = (n : ℤ) * (((n : ℤ) + 1) * m) := by
    calc
      (2 * m) * s = (2 * s) * m := by ring
      _ = ((n : ℤ) * ((n : ℤ) + 1)) * m := by rw [hs]
      _ = (n : ℤ) * (((n : ℤ) + 1) * m) := by ring
  rw [show (2 * m) * ∑ k ∈ Finset.Icc 1 n, (k : ℤ) = (2 * m) * s by rfl]
  rw [hadd]
  exact dvd_mul_right (n : ℤ) (((n : ℤ) + 1) * m)

theorem A_add_twoShift (r : ℝ) (m : ℤ) :
    A (r + twoShift m) = A r := by
  ext n
  simp only [mem_A_iff]
  constructor
  · rintro ⟨hnpos, hdiv⟩
    refine ⟨hnpos, ?_⟩
    let addend : ℤ := (2 * m) * ∑ k ∈ Finset.Icc 1 n, (k : ℤ)
    have hadd : (n : ℤ) ∣ addend := by
      simpa [addend] using dvd_shift_floorSum_addend m n
    rw [floorSum_add_twoShift] at hdiv
    have hsub : (n : ℤ) ∣ (floorSum r n + addend) - addend := by
      exact dvd_sub (by simpa [addend] using hdiv) hadd
    convert hsub using 1
    ring
  · rintro ⟨hnpos, hdiv⟩
    refine ⟨hnpos, ?_⟩
    let addend : ℤ := (2 * m) * ∑ k ∈ Finset.Icc 1 n, (k : ℤ)
    have hadd : (n : ℤ) ∣ addend := by
      simpa [addend] using dvd_shift_floorSum_addend m n
    rw [floorSum_add_twoShift]
    exact dvd_add hdiv (by simpa [addend] using hadd)

private theorem floor_neg_of_not_int {x : ℝ}
    (hnot : ∀ m : ℤ, x ≠ (m : ℝ)) :
    Int.floor (-x) = -Int.floor x - 1 := by
  rw [Int.floor_eq_iff]
  constructor
  · change ((-Int.floor x - 1 : ℤ) : ℝ) ≤ -x
    norm_num
    have hlt := Int.lt_floor_add_one x
    linarith
  · change -x < ((-Int.floor x - 1 : ℤ) : ℝ) + 1
    norm_num
    have hlt : (Int.floor x : ℝ) < x := floor_lt_of_not_int hnot
    linarith

private theorem floorMul_neg_of_irrational {r : ℝ} (hr : IsIrrational r)
    {k : ℕ} (hkpos : 0 < k) :
    floorMul (-r) k = -floorMul r k - 1 := by
  unfold floorMul
  have harg : (k : ℝ) * -r = -((k : ℝ) * r) := by ring
  rw [harg]
  exact floor_neg_of_not_int (mul_irrational_not_int hr hkpos)

private theorem floorSum_neg_of_irrational {r : ℝ} (hr : IsIrrational r)
    (n : ℕ) :
    floorSum (-r) n = -floorSum r n - (n : ℤ) := by
  unfold floorSum
  rw [Finset.sum_congr rfl (fun k hk => by
    have hkpos : 0 < k := by
      have hk' := (Finset.mem_Icc.mp hk).1
      omega
    exact floorMul_neg_of_irrational hr hkpos)]
  rw [Finset.sum_sub_distrib]
  rw [Finset.sum_neg_distrib]
  simp [Finset.sum_const]

theorem A_neg_of_irrational {r : ℝ} (hr : IsIrrational r) :
    A (-r) = A r := by
  ext n
  simp only [mem_A_iff]
  constructor
  · rintro ⟨hnpos, hdiv⟩
    refine ⟨hnpos, ?_⟩
    rw [floorSum_neg_of_irrational hr] at hdiv
    have hn_dvd_n : (n : ℤ) ∣ (n : ℤ) := dvd_refl (n : ℤ)
    have hsum : (n : ℤ) ∣ -floorSum r n := by
      have hsub : (n : ℤ) ∣ (-floorSum r n - (n : ℤ)) + (n : ℤ) := by
        exact dvd_add hdiv hn_dvd_n
      convert hsub using 1
      ring
    exact dvd_neg.mp hsum
  · rintro ⟨hnpos, hdiv⟩
    refine ⟨hnpos, ?_⟩
    rw [floorSum_neg_of_irrational hr]
    exact dvd_sub (dvd_neg.mpr hdiv) (dvd_refl (n : ℤ))

/-- The obvious symmetries preserve `A`. -/
theorem A_eq_of_mem_symmetryClass {α β : ℝ}
    (hαirr : IsIrrational α) (hβ : β ∈ symmetryClass α) :
    A β = A α := by
  rcases hβ with ⟨m, h | h⟩
  · rw [h]
    exact A_add_twoShift α m
  · rw [h]
    calc
      A (-α + twoShift m) = A (-α) := A_add_twoShift (-α) m
      _ = A α := A_neg_of_irrational hαirr

/-- The symmetry orbit preserves the literal irrationality-measure predicate. -/
theorem HasIrrationalityMeasure_of_mem_symmetryClass
    {α β μ : ℝ}
    (hμ : HasIrrationalityMeasure α μ)
    (hβ : β ∈ symmetryClass α) :
    HasIrrationalityMeasure β μ := by
  rcases hβ with ⟨m, h | h⟩
  · rw [h]
    simpa [twoShift, Int.cast_mul] using hμ.add_int (2 * m)
  · rw [h]
    simpa [twoShift, Int.cast_mul] using hμ.neg_add_int (2 * m)

/-- The additive-energy exponent of the actual floor-sum truncations is
constant on a symmetry class. -/
theorem floorSumAAdditiveEnergyExponent_eq_of_mem_symmetryClass
    {α β : ℝ}
    (hαirr : IsIrrational α)
    (hβ : β ∈ symmetryClass α) :
    floorSumAAdditiveEnergyExponent β =
      floorSumAAdditiveEnergyExponent α :=
  floorSumAAdditiveEnergyExponent_congr
    (A_eq_of_mem_symmetryClass hαirr hβ)

/-- The public `[1,N]` additive-energy exponent is also constant on a
symmetry class. -/
theorem floorSumATruncIccAdditiveEnergyExponent_eq_of_mem_symmetryClass
    {α β : ℝ}
    (hαirr : IsIrrational α)
    (hβ : β ∈ symmetryClass α) :
    floorSumATruncIccAdditiveEnergyExponent β =
      floorSumATruncIccAdditiveEnergyExponent α := by
  calc
    floorSumATruncIccAdditiveEnergyExponent β =
        floorSumAAdditiveEnergyExponent β := by
      rw [floorSumATruncIccAdditiveEnergyExponent_eq_floorSumAAdditiveEnergyExponent]
    _ = floorSumAAdditiveEnergyExponent α :=
      floorSumAAdditiveEnergyExponent_eq_of_mem_symmetryClass hαirr hβ
    _ = floorSumATruncIccAdditiveEnergyExponent α := by
      rw [floorSumATruncIccAdditiveEnergyExponent_eq_floorSumAAdditiveEnergyExponent]

/-- Orbit transitivity for the explicit symmetry class. -/
theorem symmetryClass_trans {α β γ : ℝ}
    (hβ : β ∈ symmetryClass α) (hγ : γ ∈ symmetryClass β) :
    γ ∈ symmetryClass α := by
  rcases hβ with ⟨m, hβ | hβ⟩
  · rcases hγ with ⟨n, hγ | hγ⟩
    · refine ⟨m + n, Or.inl ?_⟩
      rw [hγ, hβ]
      simp [twoShift]
      ring
    · refine ⟨n - m, Or.inr ?_⟩
      rw [hγ, hβ]
      simp [twoShift]
      ring
  · rcases hγ with ⟨n, hγ | hγ⟩
    · refine ⟨m + n, Or.inr ?_⟩
      rw [hγ, hβ]
      simp [twoShift]
      ring
    · refine ⟨n - m, Or.inl ?_⟩
      rw [hγ, hβ]
      simp [twoShift]
      ring

/-- Orbit symmetry for the explicit symmetry class. -/
theorem symmetryClass_symm {α β : ℝ}
    (hβ : β ∈ symmetryClass α) :
    α ∈ symmetryClass β := by
  rcases hβ with ⟨m, hβ | hβ⟩
  · refine ⟨-m, Or.inl ?_⟩
    rw [hβ]
    simp [twoShift]
  · refine ⟨m, Or.inr ?_⟩
    rw [hβ]
    simp [twoShift]

/-- The literal irrationality-measure predicate is invariant along a symmetry
orbit. -/
theorem HasIrrationalityMeasure_iff_of_mem_symmetryClass
    {α β μ : ℝ}
    (hβ : β ∈ symmetryClass α) :
    HasIrrationalityMeasure β μ ↔
      HasIrrationalityMeasure α μ := by
  constructor
  · intro hμ
    exact HasIrrationalityMeasure_of_mem_symmetryClass hμ
      (symmetryClass_symm hβ)
  · intro hμ
    exact HasIrrationalityMeasure_of_mem_symmetryClass hμ hβ

/-- Every irrational real has a representative in `[1,2]` with the same
`A`-set and in the same explicit symmetry orbit. -/
private theorem irrational_sub_twoShift {r : ℝ} (hr : IsIrrational r)
    (m : ℤ) :
    IsIrrational (r - twoShift m) := by
  intro hrat
  rcases hrat with ⟨q, hq⟩
  apply hr
  refine ⟨q + (2 : ℚ) * (m : ℚ), ?_⟩
  change ((q + (2 : ℚ) * (m : ℚ) : ℚ) : ℝ) = r
  rw [Rat.cast_add, Rat.cast_mul, Rat.cast_ofNat, Rat.cast_intCast, hq]
  simp [twoShift]

theorem exists_normalized_representative (r : ℝ) (hr : IsIrrational r) :
    ∃ r₀ : ℝ,
      r₀ ∈ Set.Icc (1 : ℝ) 2 ∧ A r₀ = A r ∧ r ∈ symmetryClass r₀ := by
  let m : ℤ := Int.floor (r / 2)
  let t : ℝ := r - twoShift m
  have ht0 : 0 ≤ t := by
    have h := Int.sub_floor_div_mul_nonneg r (by norm_num : (0 : ℝ) < 2)
    dsimp [t, m, twoShift]
    convert h using 1
    ring
  have ht2 : t < 2 := by
    have h := Int.sub_floor_div_mul_lt r (by norm_num : (0 : ℝ) < 2)
    dsimp [t, m, twoShift]
    convert h using 1
    ring
  have htIrr : IsIrrational t := by
    dsimp [t]
    exact irrational_sub_twoShift hr m
  have ht_eq_shift : t = r + twoShift (-m) := by
    dsimp [t, twoShift]
    norm_num
    ring
  have hAt : A t = A r := by
    rw [ht_eq_shift]
    exact A_add_twoShift r (-m)
  by_cases htge1 : (1 : ℝ) ≤ t
  · refine ⟨t, ?_, hAt, ?_⟩
    · exact ⟨htge1, le_of_lt ht2⟩
    · refine ⟨m, Or.inl ?_⟩
      dsimp [t, twoShift]
      ring
  · have htlt1 : t < 1 := lt_of_not_ge htge1
    have htpos : 0 < t := by
      refine lt_of_le_of_ne ht0 ?_
      intro hzero
      exact htIrr ⟨0, by simp [hzero.symm]⟩
    let r₀ : ℝ := -t + twoShift 1
    refine ⟨r₀, ?_, ?_, ?_⟩
    · constructor
      · dsimp [r₀, twoShift]
        norm_num
        linarith
      · dsimp [r₀, twoShift]
        norm_num
        linarith
    · calc
        A r₀ = A (-t + twoShift 1) := rfl
        _ = A (-t) := A_add_twoShift (-t) 1
        _ = A t := A_neg_of_irrational htIrr
        _ = A r := hAt
    · refine ⟨m + 1, Or.inr ?_⟩
      dsimp [r₀, t, twoShift]
      norm_num
      ring

/-- Symmetric version of the normalized representative package: the normalized
representative has the same `A`-set, the same floor-sum additive-energy
exponent, and exactly the same literal irrationality-measure predicates. -/
theorem exists_normalized_representative_additiveEnergy_measure_iff
    (r : ℝ) (hr : IsIrrational r) :
    ∃ r₀ : ℝ,
      r₀ ∈ Set.Icc (1 : ℝ) 2 ∧
        IsIrrational r₀ ∧
          A r₀ = A r ∧
            floorSumAAdditiveEnergyExponent r =
              floorSumAAdditiveEnergyExponent r₀ ∧
              (∀ μ : ℝ,
                HasIrrationalityMeasure r μ ↔
                  HasIrrationalityMeasure r₀ μ) := by
  rcases exists_normalized_representative r hr with
    ⟨r₀, hr₀I, hAr₀, hr_mem⟩
  refine ⟨r₀, hr₀I, ?_, hAr₀, ?_, ?_⟩
  · exact irrational_of_A_eq_irrational hr hAr₀
  · exact floorSumAAdditiveEnergyExponent_congr hAr₀.symm
  · intro μ
    exact HasIrrationalityMeasure_iff_of_mem_symmetryClass hr_mem

/-- Arbitrary-parameter version of the zero additive-energy exponent bridge.

After normalizing an irrational parameter into `[1,2]`, any continued-fraction
coefficient model for the normalized representative transfers the
zero-exponent/measure-`2` equivalence back to the original floor-sum set. -/
theorem exists_normalized_representative_additiveEnergy_zero_iff_cf_measure
    (r : ℝ) (hr : IsIrrational r) :
    ∃ r₀ : ℝ,
      r₀ ∈ Set.Icc (1 : ℝ) 2 ∧
        IsIrrational r₀ ∧
          A r₀ = A r ∧
            (∀ {a : ℕ → ℕ} {μ : ℝ},
              IsSimpleCFExpansion r₀ a →
                HasCanonicalBlockGrowthFormula a →
                  HasIrrationalityMeasureFromCF a μ →
                    μ ≠ 1 →
                      (floorSumAAdditiveEnergyExponent r = 0 ↔ μ = 2)) := by
  rcases exists_normalized_representative r hr with
    ⟨r₀, hr₀I, hAr₀, _hr_mem⟩
  have hr₀irr : IsIrrational r₀ :=
    irrational_of_A_eq_irrational hr hAr₀
  refine ⟨r₀, hr₀I, hr₀irr, hAr₀, ?_⟩
  intro a μ hcf hblock hμ hμne
  have hr₀pos : 0 < r₀ :=
    lt_of_lt_of_le (by norm_num : (0 : ℝ) < 1) hr₀I.1
  exact
    floorSumAAdditiveEnergyExponent_eq_zero_iff_cf_measure_eq_two_of_A_eq
      hAr₀ hr₀pos hr₀irr hcf hblock hμ hμne

/-- Public `[1,N]` truncation version of
`exists_normalized_representative_additiveEnergy_zero_iff_cf_measure`. -/
theorem exists_normalized_representative_truncIcc_additiveEnergy_zero_iff_cf_measure
    (r : ℝ) (hr : IsIrrational r) :
    ∃ r₀ : ℝ,
      r₀ ∈ Set.Icc (1 : ℝ) 2 ∧
        IsIrrational r₀ ∧
          A r₀ = A r ∧
            (∀ {a : ℕ → ℕ} {μ : ℝ},
              IsSimpleCFExpansion r₀ a →
                HasCanonicalBlockGrowthFormula a →
                  HasIrrationalityMeasureFromCF a μ →
                    μ ≠ 1 →
                      (floorSumATruncIccAdditiveEnergyExponent r = 0 ↔
                        μ = 2)) := by
  rcases exists_normalized_representative_additiveEnergy_zero_iff_cf_measure
      r hr with
    ⟨r₀, hr₀I, hr₀irr, hAr₀, hbridge⟩
  refine ⟨r₀, hr₀I, hr₀irr, hAr₀, ?_⟩
  intro a μ hcf hblock hμ hμne
  rw [floorSumATruncIccAdditiveEnergyExponent_eq_floorSumAAdditiveEnergyExponent]
  exact hbridge hcf hblock hμ hμne

/-- Literal-measure version of the normalized `[1,N]` additive-energy bridge.

This is the formally available version of the writeup's final implication:
once the normalized representative's continued-fraction coefficients satisfy
the block-growth formula and the CF-computed irrationality-measure theorem,
the zero additive-energy exponent for `A_r ∩ [1,N]` is equivalent to the
literal statement that `r` has irrationality measure `2`. -/
theorem floorSumATruncIccAdditiveEnergyExponent_eq_zero_iff_hasIrrationalityMeasure_two_of_mem_symmetryClass
    {α β : ℝ} {a : ℕ → ℕ}
    (hαpos : 0 < α)
    (hαirr : IsIrrational α)
    (hβ : β ∈ symmetryClass α)
    (hcf : IsSimpleCFExpansion α a)
    (hblock : HasCanonicalBlockGrowthFormula a)
    (hmetric :
      HasIrrationalityMeasure α (2 + partialQuotientGrowthTau a))
    (hden : 1 + partialQuotientGrowthTau a ≠ 0) :
    floorSumATruncIccAdditiveEnergyExponent β = 0 ↔
      HasIrrationalityMeasure β 2 := by
  have hExp :
      floorSumATruncIccAdditiveEnergyExponent β =
        floorSumATruncIccAdditiveEnergyExponent α :=
    floorSumATruncIccAdditiveEnergyExponent_eq_of_mem_symmetryClass
      hαirr hβ
  have hμiff :
      HasIrrationalityMeasure β 2 ↔
        HasIrrationalityMeasure α 2 :=
    HasIrrationalityMeasure_iff_of_mem_symmetryClass hβ
  rw [hExp, hμiff]
  exact
    floorSumATruncIccAdditiveEnergyExponent_eq_zero_iff_hasIrrationalityMeasure_two
      hαpos hαirr hcf hblock hmetric hden

/-- Arbitrary irrational parameters reduce to the normalized positive case for
the public `[1,N]` additive-energy exponent and literal irrationality measure.

The remaining mathematical input is exactly the classical CF metric bridge for
the normalized representative: `HasIrrationalityMeasure r₀ (2 + tau)`. -/
theorem exists_normalized_representative_truncIcc_additiveEnergy_zero_iff_hasIrrationalityMeasure_two
    (r : ℝ) (hr : IsIrrational r) :
    ∃ r₀ : ℝ,
      r₀ ∈ Set.Icc (1 : ℝ) 2 ∧
        IsIrrational r₀ ∧
          A r₀ = A r ∧
            (∀ {a : ℕ → ℕ},
              IsSimpleCFExpansion r₀ a →
                HasCanonicalBlockGrowthFormula a →
                  HasIrrationalityMeasure r₀
                    (2 + partialQuotientGrowthTau a) →
                    1 + partialQuotientGrowthTau a ≠ 0 →
                      (floorSumATruncIccAdditiveEnergyExponent r = 0 ↔
                        HasIrrationalityMeasure r 2)) := by
  rcases exists_normalized_representative r hr with
    ⟨r₀, hr₀I, hAr₀, hr_mem⟩
  have hr₀irr : IsIrrational r₀ :=
    irrational_of_A_eq_irrational hr hAr₀
  have hr₀pos : 0 < r₀ :=
    lt_of_lt_of_le (by norm_num : (0 : ℝ) < 1) hr₀I.1
  refine ⟨r₀, hr₀I, hr₀irr, hAr₀, ?_⟩
  intro a hcf hblock hmetric hden
  exact
    floorSumATruncIccAdditiveEnergyExponent_eq_zero_iff_hasIrrationalityMeasure_two_of_mem_symmetryClass
      hr₀pos hr₀irr hr_mem hcf hblock hmetric hden

/-- Finite partial-quotient-growth version of the arbitrary-parameter
normalization theorem.  The boundedness hypothesis discharges the CF metric
and block-growth inputs for the normalized representative. -/
theorem floorSumATruncIccAdditiveEnergyExponent_eq_zero_iff_hasIrrationalityMeasure_two_of_mem_symmetryClass_of_tau_bounded
    {α β : ℝ} {a : ℕ → ℕ}
    (hαpos : 0 < α)
    (hαirr : IsIrrational α)
    (hβ : β ∈ symmetryClass α)
    (hcf : IsSimpleCFExpansion α a)
    (hbounded :
      Filter.IsBoundedUnder (fun x y : ℝ => x ≤ y) Filter.atTop
        (pqLogRatio a)) :
    floorSumATruncIccAdditiveEnergyExponent β = 0 ↔
      HasIrrationalityMeasure β 2 := by
  have hExp :
      floorSumATruncIccAdditiveEnergyExponent β =
        floorSumATruncIccAdditiveEnergyExponent α :=
    floorSumATruncIccAdditiveEnergyExponent_eq_of_mem_symmetryClass
      hαirr hβ
  have hμiff :
      HasIrrationalityMeasure β 2 ↔
        HasIrrationalityMeasure α 2 :=
    HasIrrationalityMeasure_iff_of_mem_symmetryClass hβ
  rw [hExp, hμiff]
  exact
    floorSumATruncIccAdditiveEnergyExponent_eq_zero_iff_hasIrrationalityMeasure_two_of_tau_bounded
      hαpos hαirr hcf hbounded

/-- Arbitrary irrational parameters reduce to the normalized finite-growth
case for the public `[1,N]` additive-energy exponent. -/
theorem exists_normalized_representative_truncIcc_additiveEnergy_zero_iff_hasIrrationalityMeasure_two_of_tau_bounded
    (r : ℝ) (hr : IsIrrational r) :
    ∃ r₀ : ℝ,
      r₀ ∈ Set.Icc (1 : ℝ) 2 ∧
        IsIrrational r₀ ∧
          A r₀ = A r ∧
            (∀ {a : ℕ → ℕ},
              IsSimpleCFExpansion r₀ a →
                Filter.IsBoundedUnder (fun x y : ℝ => x ≤ y) Filter.atTop
                  (pqLogRatio a) →
                  (floorSumATruncIccAdditiveEnergyExponent r = 0 ↔
                    HasIrrationalityMeasure r 2)) := by
  rcases exists_normalized_representative r hr with
    ⟨r₀, hr₀I, hAr₀, hr_mem⟩
  have hr₀irr : IsIrrational r₀ :=
    irrational_of_A_eq_irrational hr hAr₀
  have hr₀pos : 0 < r₀ :=
    lt_of_lt_of_le (by norm_num : (0 : ℝ) < 1) hr₀I.1
  refine ⟨r₀, hr₀I, hr₀irr, hAr₀, ?_⟩
  intro a hcf hbounded
  exact
    floorSumATruncIccAdditiveEnergyExponent_eq_zero_iff_hasIrrationalityMeasure_two_of_mem_symmetryClass_of_tau_bounded
      hr₀pos hr₀irr hr_mem hcf hbounded

/-- Arbitrary irrational version of the additive-energy/measure-`2`
equivalence, stated in the project's logarithmic-exponent language for the
public truncations `A r ∩ [1,N]`. -/
theorem floorSumATruncIccAdditiveEnergyExponent_eq_zero_iff_hasIrrationalityMeasure_two_of_irrational
    {r : ℝ} (hr : IsIrrational r) :
    floorSumATruncIccAdditiveEnergyExponent r = 0 ↔
      HasIrrationalityMeasure r 2 := by
  rcases exists_normalized_representative r hr with
    ⟨r₀, hr₀I, hAr₀, hr_mem⟩
  have hr₀irr : IsIrrational r₀ :=
    irrational_of_A_eq_irrational hr hAr₀
  have hr₀pos : 0 < r₀ :=
    lt_of_lt_of_le (by norm_num : (0 : ℝ) < 1) hr₀I.1
  rcases exists_simpleCFExpansion_of_irrational hr₀pos hr₀irr with
    ⟨a, hcf⟩
  have hExp :
      floorSumATruncIccAdditiveEnergyExponent r =
        floorSumATruncIccAdditiveEnergyExponent r₀ :=
    floorSumATruncIccAdditiveEnergyExponent_eq_of_mem_symmetryClass
      hr₀irr hr_mem
  have hμiff :
      HasIrrationalityMeasure r 2 ↔
        HasIrrationalityMeasure r₀ 2 :=
    HasIrrationalityMeasure_iff_of_mem_symmetryClass hr_mem
  rw [hExp, hμiff]
  exact
    floorSumATruncIccAdditiveEnergyExponent_eq_zero_iff_hasIrrationalityMeasure_two_of_simpleCFExpansion
      hr₀pos hr₀irr hcf

/-- Project-language stand-in for
`E(A_r ∩ [1,N]) = N^{o(1)}`: the logarithmic additive-energy exponent is
zero. -/
def FloorSumATruncIccAdditiveEnergySubpolynomialExponent (r : ℝ) : Prop :=
  floorSumATruncIccAdditiveEnergyExponent r = 0

/-- Arbitrary irrational version in the prose theorem's sub-polynomial
language. -/
theorem floorSumATruncIccAdditiveEnergySubpolynomialExponent_iff_hasIrrationalityMeasure_two_of_irrational
    {r : ℝ} (hr : IsIrrational r) :
    FloorSumATruncIccAdditiveEnergySubpolynomialExponent r ↔
      HasIrrationalityMeasure r 2 := by
  simpa [FloorSumATruncIccAdditiveEnergySubpolynomialExponent] using
    floorSumATruncIccAdditiveEnergyExponent_eq_zero_iff_hasIrrationalityMeasure_two_of_irrational
      hr

/-- Refined finite-regime formula transported along a symmetry class.

The boundedness assumption is the project's formal version of the finite
partial-quotient-growth regime for the chosen normalized continued-fraction
coefficients. -/
theorem floorSumATruncIccAdditiveEnergyExponent_eq_three_mul_irrationalityMeasure_formula_of_mem_symmetryClass_of_bounded
    {α β μ : ℝ} {a : ℕ → ℕ}
    (hαpos : 0 < α)
    (hαirr : IsIrrational α)
    (hβ : β ∈ symmetryClass α)
    (hcf : IsSimpleCFExpansion α a)
    (hbounded :
      Filter.IsBoundedUnder (fun x y : ℝ => x ≤ y) Filter.atTop
        (pqLogRatio a))
    (hμ : HasIrrationalityMeasure β μ) :
    floorSumATruncIccAdditiveEnergyExponent β =
      3 * ((μ - 2) / (μ - 1)) := by
  have hExp :
      floorSumATruncIccAdditiveEnergyExponent β =
        floorSumATruncIccAdditiveEnergyExponent α :=
    floorSumATruncIccAdditiveEnergyExponent_eq_of_mem_symmetryClass
      hαirr hβ
  have hμα : HasIrrationalityMeasure α μ :=
    (HasIrrationalityMeasure_iff_of_mem_symmetryClass hβ).mp hμ
  rw [hExp]
  exact
    floorSumATruncIccAdditiveEnergyExponent_eq_three_mul_irrationalityMeasure_formula_of_bounded
      hαpos hαirr hcf hbounded hμα

/-- Arbitrary irrational refined exponent formula after normalization, in the
finite partial-quotient-growth regime for the normalized representative. -/
theorem exists_normalized_representative_truncIcc_additiveEnergy_formula_of_bounded
    {r μ : ℝ} (hr : IsIrrational r)
    (hμ : HasIrrationalityMeasure r μ) :
    ∃ r₀ : ℝ,
      r₀ ∈ Set.Icc (1 : ℝ) 2 ∧
        IsIrrational r₀ ∧
          A r₀ = A r ∧
            (∀ {a : ℕ → ℕ},
              IsSimpleCFExpansion r₀ a →
                Filter.IsBoundedUnder (fun x y : ℝ => x ≤ y) Filter.atTop
                  (pqLogRatio a) →
                  floorSumATruncIccAdditiveEnergyExponent r =
                    3 * ((μ - 2) / (μ - 1))) := by
  rcases exists_normalized_representative r hr with
    ⟨r₀, hr₀I, hAr₀, hr_mem⟩
  have hr₀irr : IsIrrational r₀ :=
    irrational_of_A_eq_irrational hr hAr₀
  have hr₀pos : 0 < r₀ :=
    lt_of_lt_of_le (by norm_num : (0 : ℝ) < 1) hr₀I.1
  refine ⟨r₀, hr₀I, hr₀irr, hAr₀, ?_⟩
  intro a hcf hbounded
  exact
    floorSumATruncIccAdditiveEnergyExponent_eq_three_mul_irrationalityMeasure_formula_of_mem_symmetryClass_of_bounded
      hr₀pos hr₀irr hr_mem hcf hbounded hμ

/-- If two irrational parameters have the same `A`-set, then they belong to
the same explicit symmetry orbit. -/
theorem mem_symmetryClass_of_A_eq {α β : ℝ}
    (hαirr : IsIrrational α) (hA : A β = A α) :
    β ∈ symmetryClass α := by
  have hβirr : IsIrrational β :=
    irrational_of_A_eq_irrational hαirr hA
  rcases exists_normalized_representative α hαirr with
    ⟨α₀, hα₀I, hAα₀, hαorbit⟩
  rcases exists_normalized_representative β hβirr with
    ⟨β₀, hβ₀I, hAβ₀, hβorbit⟩
  have hα₀irr : IsIrrational α₀ :=
    irrational_of_A_eq_irrational hαirr hAα₀
  have hβ₀_eq_α₀ : β₀ = α₀ := by
    exact (equivalence_class_problem_normalized_iff hα₀irr hα₀I hβ₀I).mp
      (by
        calc
          A β₀ = A β := hAβ₀
          _ = A α := hA
          _ = A α₀ := hAα₀.symm)
  subst β₀
  have hα₀_mem_α : α₀ ∈ symmetryClass α :=
    symmetryClass_symm hαorbit
  exact symmetryClass_trans hα₀_mem_α hβorbit

/-- The equivalence class problem, unnormalized form. -/
theorem equivalence_class_problem {α β : ℝ} (hαirr : IsIrrational α) :
    A β = A α ↔ β ∈ symmetryClass α := by
  constructor
  · exact mem_symmetryClass_of_A_eq hαirr
  · intro hβ
    exact A_eq_of_mem_symmetryClass hαirr hβ

/-- Set-valued version of the equivalence class theorem. -/
theorem AEquivClass_eq_symmetryClass {α : ℝ} (hαirr : IsIrrational α) :
    AEquivClass α = symmetryClass α := by
  ext β
  exact equivalence_class_problem hαirr

end IrrationalityAr
